# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    npm run scully -- --scanRoutes
    git config user.email "michel.vanveldhoven@planet.nl"
    git config user.name "michelvanveldhoven"
    npm run deploy -- -r https://$(github_pat)@github.com/michelvanveldhoven/angular-gh-pages.git
  displayName: 'npm install and build and publish'
